name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/.vitepress/dist
          single-commit: true
          clean: true
